version: "3.8"

services:
  server1:
    build: ./server1
    container_name: server1
    restart: always
    ports:
      - "5001:5000"
    networks:
      - flask_network

  server2:
    build: ./server2
    container_name: server2
    restart: always
    ports:
      - "5002:5000"
    networks:
      - flask_network

  server3:
    build: ./server3
    container_name: server3
    restart: always
    ports:
      - "5003:5000"
    networks:
      - flask_network

  server4:
    build: ./server4
    container_name: server4
    restart: always
    ports:
      - "5004:5000"
    networks:
      - flask_network

  nginx:
    image: nginx:latest
    container_name: nginx_load_balancer
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"  # Port 80 untuk akses dari luar
    depends_on:
      - server1
      - server2
      - server3
      - server4
    networks:
      - flask_network

networks:
  flask_network:
    driver: bridge
